export enum ActionTypes {
  SEARCH_REPOSITORIES = "SEARCH_REPOSITORIES",
  SEARCH_REPOSITORIES_SUCCSESS = "SEARCH_REPOSITORIES_SUCCSESS",
  SEARCH_REPOSITORIES_FAILURE = "SEARCH_REPOSITORIES_FAILURE",
}
